steps:
  - name: "gcr.io/k8s-skaffold/pack"
    id: "build-app"
    entrypoint: "pack"
    args:
      - "build"
      - "us-central1-docker.pkg.dev/root-rock-457521-e7/cloud-run-source-deploy/${_REPO_NAME}:$SHORT_SHA"
      - "--builder=gcr.io/buildpacks/builder:google-22"
      - "--publish"
      - "--tag=us-central1-docker.pkg.dev/root-rock-457521-e7/cloud-run-source-deploy/${_REPO_NAME}:latest"
      - "--previous-image=us-central1-docker.pkg.dev/root-rock-457521-e7/cloud-run-source-deploy/${_REPO_NAME}:latest"
      - "--cache-image=us-central1-docker.pkg.dev/root-rock-457521-e7/cloud-run-source-deploy/${_REPO_NAME}:cache"
      - "--env=BP_NODE_RUN_SCRIPTS=build"

  - name: "gcr.io/cloud-builders/docker"
    id: "prefetch-gcloud"
    waitFor: ["-"]
    args: ["pull", "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    id: "deploy"
    waitFor:
      - "build-app"
    entrypoint: "gcloud"
    args:
      - "run"
      - "services"
      - "update"
      - "${_REPO_NAME}"
      - "--image=us-central1-docker.pkg.dev/root-rock-457521-e7/cloud-run-source-deploy/${_REPO_NAME}:$SHORT_SHA"
      - "--region=us-central1"

options:
  logging: CLOUD_LOGGING_ONLY
